version: '3.7'

services:
  minio:
    image: quay.io/minio/minio
    ports:
      - 9001:9001
      - 9000:9000
    environment:
      MINIO_ROOT_USER: dev
      MINIO_ROOT_PASSWORD: devdevdev
    volumes:
      - ./docker-manifest.json:/tmp/manifests/docker-manifest.json
    entrypoint: 'sh'
    command:
      -c "ls /tmp/manifests/ && mkdir -p /data/manifests && cp /tmp/manifests/docker-manifest.json /data/manifests/manifest.json && minio server /data --console-address ':9001'"

  launcher:
    build:
      context: ./launcher
    ports:
      - 3000:3000
    command: ["yarn", "start-prod"]

  exchange:
    build:
      context: ./exchange
    ports:
      - 3001:3000
    command: ["yarn", "start-prod"]

  recording-oracle:
    build:
      context: ./recording-oracle
    network_mode: "host"
    environment:
      ETH_PRIVATE_KEY: 09762fa0f91726089540420b0a83c01048eb6b2ba178cafea7c12e5d96c57896
      ETH_HTTP_SERVER: https://staging-v2.skalenodes.com/v1/stocky-pleione
      PORT: 3005
    command: ["yarn", "start"]

  reputation-oracle:
    build:
      context: ./reputation-oracle
    ports:
      - 3006:3006
    environment:
      ETH_PRIVATE_KEY: 4b03dafb5fb7cef5909042fe01aa627440a9db7079d248575414dec8a9042ce0
      ETH_HTTP_SERVER: https://staging-v2.skalenodes.com/v1/stocky-pleione
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: dev
      MINIO_SECRET_KEY: devdevdev
      MINIO_BUCKET_NAME: job-results
      PORT: 3006
    command: ["yarn", "start"]
